name = "rsc-server-do"
main = "worker.js"
compatibility_date = "2024-01-01"
node_compat = true

# Durable Objects
[durable_objects]
bindings = [
    { name = "GAME_WORLD", class_name = "GameWorld" }
]

[[migrations]]
tag = "v1"
new_classes = ["GameWorld"]

# KV Namespaces
[[kv_namespaces]]
binding = "PLAYERS_KV"
id = "f2881801ac59415a86236d0841f27103"

# Environment Variables
[vars]
MEMBERS = "false"

# Local development
[env.dev]
MEMBERS = "false"
