name = "rsc-party-worker"
main = "src/index.ts"
compatibility_date = "2024-05-29"

[[durable_objects.bindings]]
name = "RSC_PARTY"
class_name = "RSCServer"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RSCServer"]
